name: BuildDockerImage
on:
  push:
    branches: [ master ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.event.repository.name }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      - name: Docker Hub login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login \
            --username "${DOCKER_USERNAME}" \
            --password-stdin
      - name: Run buildx and push
        env:
            DOCKER_REPO: oitq/${{env.IMAGE_NAME}}
        run: |
          docker buildx build \
            --output "type=image,push=true" \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --tag ${DOCKER_REPO}:latest \
            --file ./Dockerfile \
            .
      - name: Docker Hub logout
        if: always()
        run: docker logout
